### ISSUE TITLE
Component option API

### ISSUE THREAD

**Issue by franciscolourenco** [egoist/vue-persist#3]
Have you considered accepting a component option named `persist`? 
I've seen this pattern in other plugins.
It would make the usage more simple:

```js
import VuePersist from 'vue-persist'

Vue.use(VuePersist)

new Vue({
  template: '<input v-model="name" />',
  data: { name: '' },
  persist: ['name']
})
```

**Comment by egoist** [comment]
Yeah, I did think about this, and it would be easy to implement as well. Basically we need to add a mixin to automatically call `this.$persist(this.options.persist)` in `created` hook, are you interested in making a PR? 😊

**Comment by franciscolourenco** [comment]
I can, not sure when I will be able too, and something tells me you can do it in 1/10th of the time, not only because you already are familiar with the code. So feel free to do it, otherwise it might be a while 😚

**Comment by egoist** [comment]
Added in `v0.4.0`
